### ISSUE TITLE
GitHub files out of sync with AWS Documentation?

### ISSUE THREAD

**Issue by ssimontis** [awsdocs/aws-sdk-for-javascript-v3#2]
I was browsing [the v3 migration documentation page](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/migrating-to-v3.html) within the JS SDK documentation, and was going to submit a PR to fix some of the code samples which are currently missing an equals sign in assignment expressions in at least two places.

I was unable to locate the page within this repository, I only saw a V2 migration Markdown file. Pressing the "Edit on GitHub" button at the bottom of the documentation gave me a 404 error in GitHub,

The last modification for the documentation directory occurred nearly a year ago, is that documentation repo out of sync with the AWS documentation that is currently published? Or am I looking in the wrong place? Thank you.

**Comment by brmur** [comment]
@ssimontis Thanks for raising this. I have mirrored the latest version the documentation into this repo, and will do so weekly moving forward.
