### ISSUE TITLE
Install instructions missing

### ISSUE THREAD

**Issue by agostbiro** [awsdocs/aws-sdk-for-javascript-v3#62]
It'd be great if there was a one liner `npm install <package-name>` install example.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
