### ISSUE TITLE
Issue using fromCognitoIdentityPool

### ISSUE THREAD

**Issue by kchangch** [awsdocs/aws-sdk-for-javascript-v3#74]
Hi,

I have installed the package from the documentation but it seems that when I import this:

import { fromCognitoIdentityPool } from "@aws-sdk/credential-providers";

Getting these issues:

`Compiled with problems:X

ERROR in ./node_modules/@aws-sdk/credential-provider-cognito-identity/dist-es/fromCognitoIdentity.js 53:12-36

export 'CredentialsProviderError' (imported as 'CredentialsProviderError') was not found in '@aws-sdk/property-provider' (possible exports: ProviderError, chain, fromStatic, memoize)

ERROR in ./node_modules/@aws-sdk/credential-provider-cognito-identity/dist-es/fromCognitoIdentity.js 57:12-36

export 'CredentialsProviderError' (imported as 'CredentialsProviderError') was not found in '@aws-sdk/property-provider' (possible exports: ProviderError, chain, fromStatic, memoize)

ERROR in ./node_modules/@aws-sdk/credential-provider-cognito-identity/dist-es/fromCognitoIdentity.js 61:12-36

export 'CredentialsProviderError' (imported as 'CredentialsProviderError') was not found in '@aws-sdk/property-provider' (possible exports: ProviderError, chain, fromStatic, memoize)

ERROR in ./node_modules/@aws-sdk/credential-provider-cognito-identity/dist-es/fromCognitoIdentityPool.js 100:12-36

export 'CredentialsProviderError' (imported as 'CredentialsProviderError') was not found in '@aws-sdk/property-provider' (possible exports: ProviderError, chain, fromStatic, memoize)
`

**Comment by brmur** [comment]
@[kchangch](https://github.com/kchangch) Which service's examples are you using?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
