### ISSUE TITLE
Where do we specify credentials?

### ISSUE THREAD

**Issue by gavinnhh** [awsdocs/aws-sdk-for-javascript-v3#79]
https://github.com/awsdocs/aws-sdk-for-javascript-v3/blob/main/doc_source/sdk-example-javascript-syntax.md
I saw this tutorial on how to use s3 in js, but where exactly do I specify my s3 access key and secret keys tho?

**Comment by brmur** [comment]
@[Gavin-Hoang](https://github.com/Gavin-Hoang) You can specify your keys in a variety of ways. For more information, see https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/setting-credentials.html

**Comment by Gavin-Hoang** [comment]
@brmur  Thanks for the reply. I have been following this tutorial on digital ocean: https://docs.digitalocean.com/products/spaces/resources/s3-sdk-examples/ but my code keeps saying region is missing even I have region specified already.

**Comment by brmur** [comment]
@[Gavin-Hoang](https://github.com/Gavin-Hoang) I'd a quick look at that code and it looks okay to be, but I don't have time to verify 3rd party code. I'd suggest trying a simple create bucket, following this, and it will help you understand the pattern
https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/s3-example-creating-buckets.html#s3-example-creating-buckets-new-bucket-2

**Comment by Gavin-Hoang** [comment]
@brmur Thank you. Will dive into this more. 👍

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
