### ISSUE TITLE
Invalid example for creating presigned url

### ISSUE THREAD

**Issue by asmka** [awsdocs/aws-sdk-for-javascript-v3#83]
From https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/s3-example-creating-buckets.html#s3-create-presigendurl-put:

```Node
    await s3.send(new DeleteBucketCommand({ Bucket: bucketParams.Bucket }));
```

Variable `s3` is not defined. Correct name is `s3Client`.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
