### ISSUE TITLE
Recursive issue on Secrets Manager page

### ISSUE THREAD

**Issue by grantcarthew** [awsdocs/aws-sdk-for-javascript-v3#99]
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-secrets-manager/

Where is this documentation? Source? I don't care, just want to see it.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
